# Generated by Django 5.0.6 on 2024-05-13 12:11

import django.core.validators
import onetimesecret.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', onetimesecret.models.EncryptedTextField()),
                ('code', models.CharField(blank=True, max_length=10)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('days', models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='secret lifetime (in days)')),
            ],
            options={
                'verbose_name': 'secret',
                'verbose_name_plural': 'secrets',
            },
        ),
    ]
