# Generated by Django 5.0.4 on 2024-05-15 10:03

import onetimesecret.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onetimesecret', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='text',
            field=onetimesecret.models.EncryptedTextField(verbose_name='Text your secret:'),
        ),
    ]
